language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

stages:
  - check
  - build
  - e2e
  - name: release
    if: branch = master
  - name: deploy
    if: branch =~ /^\d+\.\d+(\.\d+)?$/

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: check
      script:
        - ./gradlew checkCi
    - stage: build
      script:
        - ./gradlew build --stacktrace
    - stage: e2e
      script:
        - export POLYGONAL_PLUGIN_VERSION=$TRAVIS_BUILD_ID
        - ./gradlew publishToMavenLocal -Pversion=$TRAVIS_BUILD_ID
        - cd e2e
        - chmod +x gradlew && ./gradlew verifyPolygons --info
        - cd ..
        - cd e2e-mvn
        - chmod +x mvnw && ./mvnw polygonal-architecture:verifyPolygons -e -f pom.xml -DpluginVersion=$POLYGONAL_PLUGIN_VERSION
    - stage: release
      script:
        - chmod +x next-version.sh && ./next-version.sh
    - stage: deploy
      script:
        - ./gradlew build -Pversion=$TRAVIS_BRANCH
        - ./gradlew :plugin-gradle:publishPlugins -Pversion=$TRAVIS_BRANCH -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET
        - ./gradlew :plugin-maven:bintrayUpload -Pversion=$TRAVIS_BRANCH --stacktrace