language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

stages:
  - check
  - build
  - test
  - deploy
  - release

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: check
      script: ./gradlew checkCi
    - stage: build
      script: ./gradlew build --scan -s --stacktrace
    - stage: release
      script: chmod +x next-version.sh && ./next-version.sh
      if: branch = master && pull_request = "false"
    - stage: deploy
      script: ./gradlew build -Pversion=$TRAVIS_BRANCH
    - script: ./gradlew bintrayUpload -Pversion=$TRAVIS_BRANCH
    - script: ./gradlew publishPlugins -Pversion=$TRAVIS_BRANCH -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET
      if: branch =~ /^\d+\.\d+(\.\d+)?$/


#e2e_test:
#  stage: test
#  script:
#    - cd e2e
#    - ./gradlew build